name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Verwende deinen Hauptbranch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Zip Lambda function
      run: zip -r function.zip .   # Packt deinen Lambda-Code in eine ZIP-Datei

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1  # Passe dies an deine Region an

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code --function-name CustomerSupportChatbot --zip-file fileb://function.zip

